### ISSUE TITLE
admin_cidr_ingress value

### ISSUE THREAD

**Issue by ghost** [ericdahl/hello-ecs#1]
hi first of all thanks for great exmaple, i am new to terraform and devops so i am confused what value i need to set in admin_cidr_ingress and i dont want to use elasticache how will i do that please help me out.

regards
Rajnish

**Comment by ericdahl** [comment]
> i need to set in admin_cidr_ingress

it has a description.

```bash
$ terraform apply
var.admin_cidr_ingress
  CIDR to allow tcp/22 ingress to EC2 instance

  Enter a value: 
```
it's for accessing your EC2 instance. you might want to set it to whatever http://httpbin.org/ip returns (e.g., `12.34.45.56/32`). Or enter `0.0.0.0/0` - allowing anyone to access it with the right ssh credentials - if you're not concerned with security and it's temporary

>  i dont want to use elasticache how will i do that please help me out.

delete your `elasticache.tf` file (and it's associated output), and it won't be created.  ~In fact, I'll do this now from this repo as it's not valuable in the context of a basic example~ nvm, perhaps later. the app does use it and it's interesting

**Comment by ghost** [comment]
thanks for the reply i have already figure it out :). while creating a instance it require 2 subnet for best practices(**terraform creating error for 1 subnet**), so i have added 2 subnet in configuration and its working perfectly fine.

thanks once again for this great example :+1: . it saved my life
