### ISSUE TITLE
how to copy a file in ecs instance after instance created

### ISSUE THREAD

**Issue by ghost** [ericdahl/hello-ecs#2]
i want to ssh in that instance and copy a file from my local system how would i do that, and where i need to put that code, currently i am using this code

` provisioner "remote-exec" {
    inline = [
      "cp config.text  /var/www/html/config.text",
    ]
    connection {
      host        = "${self.public_ip}"
      type        = "ssh"
      user        = "ubuntu"
      private_key = "${file("../mypem.pem")}"
      timeout     = "2m"
      agent       = false
    }
  }`

**Comment by ericdahl** [comment]
if it's a one time thing, you should probably use the `user-data` script in `aws_launch_configuration`

you can also ssh in directly if you set up your ssh key and admin subnet

However... copying files to `/var/www/html` seems like the wrong path for what you're doing. ECS is a container platfrom and the host itself should not really be doing much besides running docker. If you have a webserver, run the appropriate nginx (or whatever) docker image as an ECS service.

**Comment by ghost** [comment]
`/var/www/html` that was just an example, basically i wanted to send system logs to greylog that why i need to put some configuration file in that java ecs instance, i am using jenkins to automate the complete process so i can not directly use SSH. it is a one time process for now, can you please share an example for that

how would i pass my localfile in that `user_data`, does this work.
` resource "aws_launch_configuration" "app" {
  security_groups = [
    "${aws_security_group.instance_sg.id}",
  ]

  key_name                    = "${var.key_name}"

  image_id= "ami-028a9de0a7e353ed9"
  instance_type               = "${var.instance_type}"

  iam_instance_profile        = "${aws_iam_instance_profile.app.name}"
  user_data = <<EOF
#!/bin/bash

echo 'ECS_CLUSTER=terraform_example_ecs_cluster' > /etc/ecs/ecs.config
cp file.conf /etc/rsyslog.d/
start ecs
EOF
  associate_public_ip_address = true

  lifecycle {
    create_before_destroy = true
  }
  
} `

**Comment by ericdahl** [comment]
there are many examples online of how to set up files via user-data. I'll let you figure that out.

I'm not that familiar with greylog. But, it probably would be best to still use a container there. Specifically an ECS Daemon service (1 per host) and it could have read-only mounts to the host system logs.

**Comment by ghost** [comment]
any updates on copy file from user-data ?

**Comment by ericdahl** [comment]
Closing

It seems like you're not doing your own research

**Comment by ghost** [comment]
i have tried multiple sample but none of those works for me, so i was working on other part, i need your help
